[[main]]
  name = "Leistungen"
  pageRef = "/services/"
  weight = 10

[[main]]
  name = "Kontakt"
  pageRef = "/contacts/"
  weight = 20

[[footer]]
  name = "Nutzungsbedingungen"
  pageRef = "terms"
  weight = 10

[[footer]]
  name = "Datenschutz"
  pageRef = "privacy"
  weight = 20
